import { COLORS } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 24,
  },
  title: {
    fontSize: 32,
    fontWeight: 600,
  },
  alarmButton: {
    padding: 5,
    backgroundColor: COLORS.white,
    borderRadius: 50,
    height: 50,
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hideAllFilter: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  filterContainer: {
    marginTop: 24,
    marginHorizontal: 24,
    backgroundColor: COLORS.white,
    borderRadius: 100,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    height: 64,
    zIndex: 2,
  },
  filterMenu: {
    flexDirection: "row",
    alignItems: 'center',
  },
  filterMenuText: {
    fontSize: 18,
    fontWeight: 600,
    marginRight: 4,
  },
  filterContent:{
    position: 'absolute',
    zIndex: 3,
    width: 'auto',
    top: 30,
    backgroundColor: COLORS.white,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: COLORS.darkGrey,
    borderRadius: 10,
  },
  filterContentList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 4,
  },
  filterContentText: {
    fontWeight: 500,
    marginRight: 8,
  },
  dateContainer: {
    marginTop: 24,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    height: 80,
    alignItems: "center",
  },
  showAllDateButton: {
    position: "absolute",
    zIndex: 1,
    marginLeft: 10,
    width: 72,
    height: 60,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  showAllDateButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: 600,
  },
  dateContentContainer: {
    flexDirection: "row",
    paddingHorizontal: 10,
    alignItems: "center",
  },
  dates: {
    flex: 1,
    height: 80,
    marginLeft: 82,
  },
  dateItem: {
    width: 50,
    alignItems: 'center',
    marginRight: 15,
    paddingVertical: 10,
  },
  todayDateTime: {
    backgroundColor: COLORS.primary, // 오늘 날짜 배경색
    borderRadius: 10,
  },
  dayText: {
    fontSize: 14,
    color: COLORS.grey,
  },
  todayDayText: {
    color: "white",
  },
  dateText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 4,
    color: COLORS.darkGrey,
  },
  todayDateText: {
    color: COLORS.white,
  },
  post: {
    flexDirection: "row",
    height: 120,
    marginVertical: 6,
    marginHorizontal: 12,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    elevation: 1,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    alignItems: 'center',
    paddingRight: 12,
  },
  postLike: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 1,
  },
  postImg: {
    width: 96,
    height: 96,
    margin: 12,
    borderRadius: 10,
    flexShrink: 0,
  },
  postContent: {
    flex: 1,
    paddingVertical: 16,
    justifyContent: 'space-between',
    height: '100%',
  },
  postTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  postCondition: {
    flexDirection: "row",
  },
  postConditionTitle: {
    fontSize: 11,
    marginLeft: 4,
    color: COLORS.grey,
  },
  postConditionText: {
    fontSize: 11,
    marginLeft: 4,
  },
  FAB: {
    position: 'absolute',
    left: "76%",
    bottom: "3%",
    width: 64,
    height: 64,
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center'
  },
});